export const RECEIVE_DECKS = "RECEIVE_DECKS";
export const ADD_DECK = "ADD_DECK";
export const REMOVE_DECK = "REMOVE_DECK";
export const EDIT_TITLE = "EDIT_TITLE";

export const ADD_CARD = "ADD_CARD";
export const REMOVE_CARD = "REMOVE_CARD";
export const EDIT_CARD = "EDIT_CARD";

export const SET_ACTIVE_DECK = "SET_ACTIVE_DECK";
export const CLEAR_ACTIVE_DECK = "CLEAR_ACTIVE_DECK";

export const SET_ACTIVE_CARD = "SET_ACTIVE_CARD";
export const CLEAR_ACTIVE_CARD = "CLEAR_ACTIVE_CARD";

export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";

export const RECEIVE_CATEGORIES = "RECEIVE_CATEGORIES";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";
export const ADD_DECK_TO_CATEGORY = "ADD_DECK_TO_CATEGORY";
export const REMOVE_DECK_FROM_CATEGORY = "REMOVE_DECK_FROM_CATEGORY";
